[package]
name = "mod-arith-groups"
version = "0.1.0"
edition = "2021"

[dependencies]
crypto-shared = { path = "../../../shared" }
num-bigint = { workspace = true }
num-traits = { workspace = true }
rand = { workspace = true }
